import React, { useState } from 'react';
import { Plus, Minus } from 'lucide-react';

interface FAQItem {
  question: string;
  answer: string;
}

const FAQAccordion: React.FC = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const faqData: FAQItem[] = [
    {
      question: 'What is NOLIMITT?',
      answer:
        'NOLIMITT is a platform that provides innovative solutions for your needs. We offer cutting-edge technology and services designed to help you achieve your goals without limitations.',
    },
    {
      question: 'Can I use the images generated by the platform for commercial purposes?',
      answer:
        'Yes, you can use the images generated by our platform for commercial purposes, subject to our terms of service. Please review our licensing agreement for specific usage rights and restrictions.',
    },
    {
      question: 'What payment options are available?',
      answer:
        'We accept various payment methods including credit cards, debit cards, PayPal, and other popular payment processors. You can choose your preferred method during checkout.',
    },
    {
      question: 'Is there a free trial?',
      answer:
        'Yes, we offer a free trial period so you can explore our platform and features before committing to a paid plan. Sign up today to get started!',
    },
    {
      question: 'Can I cancel my Plan?',
      answer:
        'Yes, you can cancel your plan at any time from your account settings. Your access will continue until the end of your current billing period.',
    },
    {
      question: 'Can I upgrade or downgrade my current plan?',
      answer:
        'Absolutely! You can upgrade or downgrade your plan at any time. Changes will be reflected in your next billing cycle, or you can pay the difference for immediate upgrades.',
    },
    {
      question: 'What is refund policy?',
      answer:
        "We offer a 30-day money-back guarantee for all our plans. If you're not satisfied with our service, contact our support team for a full refund within the first 30 days.",
    },
  ];

  const toggleAccordion = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <div className="w-full text-white">
      <div className="max-w-6xl mx-auto">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 lg:gap-12 items-start">
          {/* Left Section - Title */}
          <div className="lg:sticky lg:top-8">
            <h2 className="text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-bold leading-tight">
              Your<br />
              questions,<br />
              answered!
            </h2>
          </div>

          {/* Right Section - FAQ Items */}
          <div className="space-y-2">
            {faqData.map((item, index) => (
              <div key={index} className="border-b border-gray-800 last:border-b-0">
                <button
                  onClick={() => toggleAccordion(index)}
                  className="w-full flex items-center justify-between py-5 px-2 text-left hover:bg-gray-900/30 transition-colors duration-200 group"
                  aria-expanded={openIndex === index}
                >
                  <span className="text-sm sm:text-base md:text-lg pr-4 text-gray-200 group-hover:text-white transition-colors">
                    {item.question}
                  </span>
                  <div
                    className={`relative flex-shrink-0 w-6 h-6 rounded-full border border-gray-600 flex items-center justify-center transition-colors duration-300 ${
                      openIndex === index ? 'bg-gray-800 border-gray-500' : ''
                    }`}
                  >
                    <Plus
                      className={`w-4 h-4 text-gray-400 transition-all duration-300 transform ${
                        openIndex === index ? 'opacity-0 scale-75 rotate-90' : 'opacity-100 scale-100 rotate-0'
                      }`}
                    />
                    <Minus
                      className={`w-4 h-4 text-gray-300 transition-all duration-300 transform absolute ${
                        openIndex === index ? 'opacity-100 scale-100 rotate-0' : 'opacity-0 scale-75 -rotate-90'
                      }`}
                    />
                  </div>
                </button>

                <div
                  className={`overflow-hidden transition-all duration-300 ease-in-out ${
                    openIndex === index ? 'max-h-96 opacity-100' : 'max-h-0 opacity-0'
                  }`}
                >
                  <div className="px-2 pb-5 text-sm sm:text-base text-gray-400 leading-relaxed">
                    {item.answer}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

export default FAQAccordion;


